export const bookInit = [
  { id: 1, title: 'Quyền sách yêu thích nhất', },
  { id: 2, title: 'Cốt truyện hay nhất' },
  { id: 3, title: 'Bìa đẹp nhất' },
  { id: 4, title: 'Quyền sách bạn sẽ đọc' },
  { id: 5, title: 'Quyển sách bạn sẽ gọi ý cho mọi người' },
  { id: 6, title: 'Quyển sách dày nhất' },
  { id: 7, title: 'Bạn ghét nhưng mọi người thích' },
  { id: 8, title: 'Bạn thích nhưng mọi người ghét' },
  { id: 9, title: 'Bị đánh giá thấp/không nổi tiếng' },
  { id: 10, title: 'Được đánh giá cao nhưng lại bình thường' },
  { id: 11, title: 'Có nhiều kiển thức/thông tin bổ ích' },
  { id: 12, title: 'Quyển sách có ảnh hưởng lớn tới bạn' },
  { id: 13, title: 'Quyển sách làm bạn khóc' },
  { id: 14, title: 'Quyền sách có nội dung chữa lành' },
  { id: 15, title: 'Hay hơn kì vọng' },
  { id: 16, title: 'Không như kì vọng' },
  { id: 17, title: 'Nhân vật chinh bạn thích nhất' },
  { id: 18, title: 'Plot twist sốc nhất' },
  { id: 19, title: 'Quyền sách bạn đã đọc lại nhiều lần' },
  { id: 20, title: 'Quyền sách bạn không đọc hết' },
  { id: 21, title: 'Tác giả yêu thích' },
  { id: 22, title: 'Đã được chuyển thể thành phim' },
  { id: 23, title: 'Series truyện yêu thích' },
  { id: 24, title: 'Không phải thể loại bạn hay đọc' },
];